name: Comparative Test Report

on:
  workflow_dispatch:

jobs:
  test-v1:
    name: Test AI DeepSeek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ai-version-1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyyaml
      - name: Run Generator
        run: python generator/gen_tests.py --config config.yaml
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: dotnet test --verbosity normal --logger "trx"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nunit-results-deepseek
          path: '**/*.trx'

  test-v2:
    name: Test AI GigaChat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ai-version-2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyyaml
      - name: Run Generator
        run: python generator/gen_tests.py --config config.yaml
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: dotnet test --verbosity normal --logger "trx"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nunit-results-gigachat
          path: '**/*.trx'

  test-v3:
    name: Test AI Qwen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ai-version-3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyyaml
      - name: Run Generator
        run: python generator/gen_tests.py --config config.yaml
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: dotnet test --verbosity normal --logger "trx"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nunit-results-qwen
          path: '**/*.trx'
